#!/usr/bin/env /opt/chefdk/embedded/bin/ruby

# Script receives this line on stdin when called for each commit
# < old-value > SP < new-value > SP < ref-name > LF
# http://stackoverflow.com/questions/2569960/git-pre-receive-hook

# Simple function, just for ease of testing
def correct_message?(msg)
  msg.include?("super")
end

# enforced custom commit message format
def check_message_format
  missed_revs = `git rev-list #{$rev_old}..#{$rev_new}`.split("\n")
  missed_revs.each do |rev|
    message = `git cat-file commit #{rev} | sed '1,/^$/d'`
      if correct_message?(message)
        return
      end
  end
  STDERR.puts "[git-hook] Your commit #{ rev } was rejected."
  STDERR.puts "[git-hook] Does it contain super?"
  exit 1
end

# The "main" method ... when executing this file:
#Only run this if the file itself is being executed
if __FILE__ == $0
  $rev_old, $rev_new, $ref = STDIN.read.split(" ")
  check_message_format
end
